#include <iostream>
#include <Windows.h>
#include <conio.h>
using namespace std;
void main()
{
	setlocale(0, "ru");
	int color_text = 0, color_fon = 0;
	HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleCursorPosition(h, { 25, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 2 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 3 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 4 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25,5 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25,6 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25,7 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 8 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 9 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 10 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 11 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 12 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 13 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, {25, 14 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 15 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 16 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 17 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 18 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25, 19 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 25,20 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";// граница левая
	SetConsoleCursorPosition(h, { 26, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 27, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 28, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 29, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 30, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 31, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 32, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 33, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 34, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 35, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 36, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 37, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 38, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 39, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 40, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 41, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 42, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 43, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 1 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";// верхняя линия
	SetConsoleCursorPosition(h, { 44, 2 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 3 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 4 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 5 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 6 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 7 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 8 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 9 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 10 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 11 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 12 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 13 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 14 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 15 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 16 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 17 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 18 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 19 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 20 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";// правая линия
	SetConsoleCursorPosition(h, { 25, 21});
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 26, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 27, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 28, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 29, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 30, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 31, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, {32, 21});
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 33, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 34, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 35, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 36, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 37, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 38, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 39, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 40, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 41, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 42, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 43, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 44, 21 });
	SetConsoleTextAttribute(h, 9 * 16 + 15);
	cout << "##";
	SetConsoleCursorPosition(h, { 28, 2 });
	SetConsoleTextAttribute(h, 20 * 16 + 15);
	cout << "С НОВЫМ ГОДОМ!";//Text
	SetConsoleCursorPosition(h, { 27, 17 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "////////\\\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 28, 16 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "///////\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 29, 15 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "//////\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 28, 14 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "///////\\\\\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 27, 13 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "////////\\\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 28, 12 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "///////\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 27, 11 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "////////\\\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 28, 10 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "///////\\\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 30, 9 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "/////\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 29, 8 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "//////\\\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 30, 7 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "/////\\\\\\\\\\";
	SetConsoleCursorPosition(h, { 31, 6 });
	SetConsoleTextAttribute(h, 12 * 3 + 7);
	cout << "////\\\\\\\\";
	SetConsoleCursorPosition(h, { 33, 5 });
	SetConsoleTextAttribute(h, 15 * 16 + 9);
	cout << "****";
	SetConsoleCursorPosition(h, { 34, 4 });
	SetConsoleTextAttribute(h, 15 * 16 + 9);
	cout << "**";
	SetConsoleCursorPosition(h, { 33, 18 });
	SetConsoleTextAttribute(h, 21 * 3 + 4);
	cout << "(||)";
	SetConsoleCursorPosition(h, { 33, 19 });
	SetConsoleTextAttribute(h, 21 * 3 + 4);
	cout << "(||)";
	SetConsoleCursorPosition(h, { 33, 20 });
	SetConsoleTextAttribute(h, 21 * 3 + 4);
	cout << "(||)";//елка
	char i = 0;
	SetConsoleCursorPosition(h, { 28, 20 });
	SetConsoleTextAttribute(h, 20 * 16);
	cout << i;
	SetConsoleCursorPosition(h, { 28, 19 });
	SetConsoleTextAttribute(h, 20 * 16);
	cout << i;
	SetConsoleCursorPosition(h, { 30, 19 });
	SetConsoleTextAttribute(h, 20 * 16);
	cout << i;
	SetConsoleCursorPosition(h, { 30, 20 });
	SetConsoleTextAttribute(h, 20 * 16);
	cout << i;
	SetConsoleCursorPosition(h, { 29, 19 });
	SetConsoleTextAttribute(h, 20 * 16 + 110);
	cout << "*";
	SetConsoleCursorPosition(h, { 29, 20 });
	SetConsoleTextAttribute(h, 20 * 16 + 110);
	cout << "*"; 
	char d = 31;
	SetConsoleCursorPosition(h, { 27, 12 });
	SetConsoleTextAttribute(h, 14);
	cout << d;
	SetConsoleCursorPosition(h, { 42, 12 });
	SetConsoleTextAttribute(h, 14);
	cout << d;
	SetConsoleCursorPosition(h, { 40, 9 });
	SetConsoleTextAttribute(h, 13);
	cout << d;
	SetConsoleCursorPosition(h, { 29, 9 });
	SetConsoleTextAttribute(h, 13);
	cout << d;
	SetConsoleCursorPosition(h, { 27, 14 });
	SetConsoleTextAttribute(h, 7);
	cout << d;
	SetConsoleCursorPosition(h, { 28, 15 });
	SetConsoleTextAttribute(h, 11);
	cout << d;
	SetConsoleCursorPosition(h, { 41, 15 });
	SetConsoleTextAttribute(h, 11);
	cout << d;
	SetConsoleCursorPosition(h, { 42, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 41, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 40, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 39, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 38, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 37, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 32, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 31, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 30, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 29, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 28, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 27, 18 });
	SetConsoleTextAttribute(h, 2);
	cout << d;
	SetConsoleCursorPosition(h, { 41, 20 });
	SetConsoleTextAttribute(h, 20 * 34);
	cout << i;
	SetConsoleCursorPosition(h, { 41, 19 });
	SetConsoleTextAttribute(h, 20 * 34);
	cout << i;
	SetConsoleCursorPosition(h, { 39, 20 });
	SetConsoleTextAttribute(h, 20 * 34);
	cout << i;
	SetConsoleCursorPosition(h, { 39, 19 });
	SetConsoleTextAttribute(h, 20 * 34);
	cout << i;
	SetConsoleCursorPosition(h, { 40, 20 });
	SetConsoleTextAttribute(h, 9 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 40, 19 });
	SetConsoleTextAttribute(h, 9 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 38, 4 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 42, 5 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 40, 6 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 31, 4 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 28, 5 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 29, 6 });
	SetConsoleTextAttribute(h, 15);
	cout << "*";
	SetConsoleCursorPosition(h, { 26, 22 });
	SetConsoleTextAttribute(h, 15);
	cout << "Andrew Lykianchikov";
	system("pause >> NUL");
}